import { StyleSheet } from 'react-native';

const authStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#070707',
  },
  backgroundBase: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#090909',
  },
  backgroundGlowTop: {
    position: 'absolute',
    width: 320,
    height: 320,
    borderRadius: 160,
    top: -120,
    right: -90,
    backgroundColor: 'rgba(203, 30, 47, 0.28)',
  },
  backgroundGlowBottom: {
    position: 'absolute',
    width: 340,
    height: 340,
    borderRadius: 170,
    bottom: -150,
    left: -120,
    backgroundColor: 'rgba(149, 25, 27, 0.24)',
  },
  shell: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 20,
  },

  card: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#3A2B10',
    backgroundColor: 'rgba(17,17,17,0.94)',
    padding: 20,
    gap: 10,
    shadowColor: '#7D0C15',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.45,
    shadowRadius: 20,
    elevation: 10,
  },
  brandIcon: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    backgroundColor: '#7D0C15',
    borderWidth: 1,
    borderColor: '#E7C989',
    marginBottom: 2,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: '#FDF5E6',
    textAlign: 'center',
  },
  subtitle: {
    color: '#C4B18A',
    textAlign: 'center',
    marginBottom: 12,
  },
  roleSelector: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 6,
  },
  roleButton: {
    flex: 1,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#3B3B3B',
    backgroundColor: '#151515',
  },
  roleButtonActive: {
    borderColor: '#E7C989',
    backgroundColor: '#8C111B',
  },
  roleButtonText: {
    color: '#CBCBCB',
    fontWeight: '700',
  },
  roleButtonTextActive: {
    color: '#FDF5E6',
  },
  label: {
    color: '#EFE0BF',
    fontSize: 13,
    marginTop: 2,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#4C3A1B',
    backgroundColor: '#171717',
    paddingHorizontal: 12,
  },
  input: {
    flex: 1,
    color: '#FDF5E6',
    height: 46,
  },
  primaryButton: {
    marginTop: 8,
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    backgroundColor: '#AE1A24',
    borderWidth: 1,
    borderColor: '#E7C989',
  },
  primaryButtonText: {
    color: '#FDF5E6',
    fontWeight: '700',
    fontSize: 15,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  inlineRow: {
    marginTop: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  mutedText: {
    color: '#B7A47E',
  },
  linkText: {
    color: '#F5C16C',
    fontWeight: '700',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },

  iconButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    borderColor: '#4C3A1B',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1A1A1A',
  },
  iconButtonPlaceholder: {
    width: 34,
    height: 34,
  },
  errorText: {
    color: '#F7A3A3',
    fontSize: 12,
    marginTop: 2,
  },
  dashboardShell: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 20,
    backgroundColor: '#070707',
  },
  dashboardCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#3A2B10',
    backgroundColor: '#111111',
    padding: 20,
    gap: 16,
  },
  dashboardTitle: {
    fontSize: 30,
    fontWeight: '700',
    color: '#FDF5E6',
    textAlign: 'center',
  },
  statGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  statCard: {
    flex: 1,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#4C3A1B',
    backgroundColor: '#171717',
    padding: 12,
    gap: 4,
  },
  statLabel: {
    color: '#BAA06A',
    fontSize: 12,
  },
  statValue: {
    color: '#FDF5E6',
    fontWeight: '700',
    fontSize: 16,
  },
  secondaryButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#7D0C15',
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1A1212',
  },
  secondaryButtonText: {
    color: '#F1B6B6',
    fontWeight: '700',
  },
});

export default authStyles;
